apiVersion: v1
kind: Service
metadata:
  name: docker-api_my_api-svc
spec:
  type: LoadBalancer
  selector:
    app: docker-api_my_api
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 8009